### ISSUE TITLE
New locomotion system breaks builds

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/XRTK-Core#884]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

When using the com.xrtk.core 0.3.0-preview.24 package I'm getting the following when building my project:

```
System.Exception: Interface XRTK.Interfaces.IMixedRealityService method System.String XRTK.Interfaces.IMixedRealityService::get_Name() not implemented on non-abstract class XRTK.Services.LocomotionSystem.LocomotionSystem
   at Unity.IL2CPP.Metadata.VTableBuilder.ValidateInterfaceMethodSlots(TypeDefinition typeDefinition, Dictionary`2 interfaceOffsets, List`1 slots)
   at Unity.IL2CPP.Metadata.VTableBuilder.VTableForType(ReadOnlyContext context, TypeDefinition typeDefinition, Dictionary`2 interfaceOffsets, Int32 currentSlot)
   at Unity.IL2CPP.Metadata.VTableBuilder.VTableFor(ReadOnlyContext context, TypeReference typeReference)
   at Unity.IL2CPP.AssemblyConversion.PrimaryCollection.Steps.PerAssembly.AssemblyCollection.CollectGenericMethodsFromVTableSlots(GlobalPrimaryCollectionContext context, AssemblyDefinition item)
   at Unity.IL2CPP.AssemblyConversion.PrimaryCollection.Steps.PerAssembly.AssemblyCollection.ProcessItem(GlobalPrimaryCollectionContext context, AssemblyDefinition item)
   at Unity.IL2CPP.AssemblyConversion.Steps.Base.ScheduledItemsStepFunc`5.WorkerWrapper(WorkItemData`3 workerData)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.ContinueWithResultsWorkItem`4.InvokeWorker(Object context, Int32 uniqueId)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.BaseContinueWorkItem`2.Invoke(Object context, Int32 uniqueId)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data)
```

## To Reproduce

1. Import latest preview package into a project
2. Build project
3. See error

## Expected behavior

No errors on build

## Actual behavior

Build does not complete

**Comment by FejZa** [comment]
I will look into this.

**Comment by FejZa** [comment]
I cannot reproduce this. Everything builds and works fine for me with the preview packages.
- Created new Unity project
- Installed XRTK.Core
- Build -> Success
- Installed XRTK.SDK
- Build -> Success

Can you add more reproduction steps?

**Comment by StephenHodgson** [comment]
I'll double check if it's still a problem on my production CI/CD

**Comment by FejZa** [comment]
Any news on this?

**Comment by StephenHodgson** [comment]
I haven't had time to test, sorry. I'll update as soon as I know more.

**Comment by StephenHodgson** [comment]
I think it was a false positive of some kind.
